import React, { useState } from "react";
import { useParams, Link } from "react-router-dom";
import "../assets/serviceListPage.css";

const ServicesListPage = () => {
  const { service } = useParams();

  const servicesData = {
    electrician: [
      "Light Fixture Installation",
      "Circuit Breaker Replacement",
      "GFCI Outlet Installation",
      "Electrical Troubleshooting",
      "Outdoor Lighting Installation",
      "Electrical Panel Upgrade",
      "Electrical Safety Inspections",
      "Wiring and Rewiring",
      "Smoke Detector Installation",
      "Surge Protector Installation",
      "Appliance Wiring",
      "Generator Installation",
      "Data and Networking Wiring",
      "Security System Wiring",
      "Electrical Code Compliance",
      "Home Automation Setup",
      "Emergency Electrical Repairs",
      "Electrical Consultations",
    ],

    plumber: [
      "Leak Repair",
      "Pipe Installation",
      "Clogged Drain Cleaning",
      "Toilet Repair and Installation",
      "Faucet Repair and Installation",
      "Water Heater Repair and Installation",
      "Sewer Line Repair",
      "Water Line Installation",
      "Garbage Disposal Repair and Installation",
      "Shower and Bathtub Installation",
      "Sink Installation",
      "Plumbing Inspections",
      "Backflow Prevention",
      "Sump Pump Installation and Repair",
      "Gas Line Repair and Installation",
      "Water Pressure Regulation",
      "Water Filtration System Installation",
      "Plumbing Fixture Upgrades",
      "Bathroom and Kitchen Remodeling",
      "Frozen Pipe Thawing and Repair",
      "Septic Tank Maintenance",
      "Grease Trap Installation and Cleaning",
      "Plumbing Emergency Services",
    ],

    mechanic: [
      "Oil Change",
      "Tire Rotation and Balancing",
      "Brake Inspection and Repair",
      "Engine Diagnostics",
      "Car Battery Replacement",
      "Alternator Replacement",
      "Starter Motor Repair and Replacement",
      "Transmission Service",
      "Radiator Repair and Flushing",
      "Air Conditioning System Service",
      "Wheel Alignment",
      "Suspension Repair",
      "Exhaust System Repair",
      "Fuel System Cleaning",
      "Spark Plug Replacement",
      "Timing Belt Replacement",
      "Ignition Coil Replacement",
      "Power Window and Door Lock Repair",
      "Car Electrical System Diagnosis and Repair",
      "Car Computer Reprogramming",
      "Pre-Purchase Car Inspection",
      "Vehicle Safety Inspections",
      "Tune-ups and Preventive Maintenance",
      "Engine Overhaul and Rebuilding",
      "Clutch Replacement",
      "Steering System Repair",
      "Car Detailing and Cleaning",
    ],
    home_cleaner: [
      "Dusting and Polishing Furniture",
      "Vacuuming and Sweeping Floors",
      "Mopping and Cleaning Hard Surfaces",
      "Bathroom Cleaning and Sanitization",
      "Kitchen Cleaning (Countertops, Sink, Appliances)",
      "Cleaning Interior Windows and Mirrors",
      "Bed Making and Linen Changing",
      "Trash Removal and Recycling",
      "Dishwashing",
      "Laundry and Ironing",
      "Organization and Decluttering",
      "Deep Cleaning (Spring Cleaning)",
      "Carpet Cleaning (Vacuuming and Spot Treatment)",
      "Upholstery Cleaning",
      "Pet Hair Removal",
      "Blind and Curtain Cleaning",
      "Ceiling Fan and Light Fixture Dusting",
      "Cabinet and Drawer Wiping",
      "Fridge and Oven Cleaning",
      "Baseboard Cleaning",
      "Wall Spot Cleaning",
      "Window Sill and Ledge Cleaning",
      "Air Purification (Air Freshening)",
      "Move-in/Move-out Cleaning",
      "After-Party Cleaning",
      "Post-Construction Cleaning",
      "Green Cleaning (Environmentally Friendly)",
      "Specialty Cleaning Services (e.g., Antiques, Delicate Items)",
    ],

    salon_services: [
      "Haircut",
      "Hairstyling (Blowout, Curling, Straightening)",
      "Hair Color (Highlights, Balayage, Full Color)",
      "Hair Extensions",
      "Hair Treatment (Deep Conditioning, Scalp Massage)",
      "Hair Updos and Special Occasion Styling",
      "Manicure",
      "Pedicure",
      "Gel Nail Polish Application",
      "Acrylic or Gel Nail Extensions",
      "Nail Art and Design",
      "Facial",
      "Skin Cleansing and Exfoliation",
      "Facial Masks and Treatments",
      "Eyebrow Shaping and Tinting",
      "Eyelash Extensions",
      "Eyelash and Eyebrow Tinting",
      "Makeup Application (Everyday, Special Occasions)",
      "Waxing (Eyebrows, Lip, Chin, Legs, Bikini, etc.)",
      "Threading (Eyebrows, Facial Hair)",
      "Body Massage (Swedish, Deep Tissue, Aromatherapy)",
      "Body Scrubs and Wraps",
      "Tanning Services (Spray Tanning, Tanning Beds)",
      "Permanent Makeup (Microblading, Lip Liner, etc.)",
      "Hair Removal (Laser Hair Removal)",
      "Barber Services (Men's Haircuts and Styling)",
      "Bridal and Wedding Packages",
      "Spa Packages (Combining Multiple Services)",
      "Nail and Hair Extensions Removal",
      "Eyelash Extensions Refills",
      "Hair and Scalp Analysis and Consultation",
    ],

    appliance_repair: [
      "Refrigerator Repair",
      "Freezer Repair",
      "Oven Repair",
      "Stove and Range Repair",
      "Microwave Repair",
      "Dishwasher Repair",
      "Washing Machine Repair",
      "Dryer Repair",
      "Garbage Disposal Repair",
      "Ice Maker Repair",
      "Wine Cooler Repair",
      "Air Conditioner Repair",
      "Heating System Repair",
      "Water Heater Repair",
      "Trash Compactor Repair",
      "Vent Hood Repair",
      "Garage Door Opener Repair",
      "Appliance Installation",
      "Appliance Maintenance",
      "Appliance Diagnostic and Troubleshooting",
      "Electronic Control Board Repair and Replacement",
      "Motor and Compressor Repair and Replacement",
      "Door Seal and Gasket Replacement",
      "Water Inlet Valve Replacement",
      "Heating Element Replacement",
      "Thermostat Repair and Replacement",
      "Belt and Pulley Replacement",
      "Timer and Control Knob Replacement",
      "Appliance Cleaning and Tune-Up",
      "Appliance Parts Ordering and Replacement",
      "Safety Inspections for Appliances",
      "Appliance Energy Efficiency Upgrades",
      "Home Appliance Consultations",
    ],
    bathroom_cleaner: [
      "Toilet Cleaning and Sanitization",
      "Sink Cleaning and Polishing",
      "Bathtub and Shower Cleaning",
      "Tile and Grout Cleaning",
      "Vanity Cleaning",
      "Mirror and Glass Cleaning",
      "Faucet and Fixture Cleaning",
      "Showerhead Descaling",
      "Shower Glass Door Cleaning",
      "Shower Curtain Cleaning",
      "Toilet Bowl Stain Removal",
      "Mold and Mildew Removal",
      "Disinfection and Sanitization",
      "Floor Cleaning and Mopping",
      "Baseboard Cleaning",
      "Trash Removal",
      "Dusting of Bathroom Fixtures",
      "Air Freshening and Deodorizing",
      "Organizing Bathroom Items",
      "Cleaning of Exhaust Fan and Ventilation",
      "Grout Sealing and Re-caulking",
      "Scrubbing of Soap Scum",
      "Cleaning of Bathroom Accessories (Toothbrush Holder, Soap Dispenser, etc.)",
      "Cleaning and Sanitization of Trash Cans",
      "Deep Cleaning Services",
      "Routine Maintenance Cleaning",
      "Green Cleaning (Environmentally Friendly Products)",
      "Post-Renovation Bathroom Cleaning",
      "Specialty Cleaning Services (e.g., Antique Fixtures, Delicate Surfaces)",
    ],
    painter: [
      "Interior Painting",
      "Exterior Painting",
      "Wall Painting",
      "Ceiling Painting",
      "Trim and Baseboard Painting",
      "Door Painting",
      "Window Painting",
      "Cabinet Painting",
      "Deck and Fence Painting",
      "Stucco Painting",
      "Siding Painting",
      "Wood and Metal Surface Painting",
      "Priming and Preparing Surfaces",
      "Color Consultation",
      "Wallpaper Removal",
      "Textured Paint Application",
      "Faux Finishes",
      "Specialty Paint Effects",
      "Power Washing (to prepare surfaces for painting)",
      "Paint Removal and Stripping",
      "Drywall Repair and Patching",
      "Plaster Repair",
      "Caulking and Sealing",
      "Paint Touch-Ups and Repairs",
      "Surface Cleaning and Preparation",
      "Epoxy Floor Coatings",
      "Spray Painting",
      "Weatherproofing and Waterproofing",
      "Fire and Smoke Damage Repair and Painting",
      "Painting High Ceilings or Difficult-to-Reach Areas",
      "Color Matching and Mixing",
      "Residential Painting Services",
      "Commercial Painting Services",
      "Industrial Painting Services",
      "Painting Consultation and Estimates",
      "Green Painting (Environmentally Friendly Paints)",
      "Painting Maintenance and Touch-Up Plans",
    ],
    gardening_services: [
      "Lawn Mowing",
      "Edging and Trimming",
      "Weeding and Weed Control",
      "Planting and Transplanting",
      "Mulching",
      "Pruning and Trimming Trees and Shrubs",
      "Hedge Trimming",
      "Fertilizing and Soil Conditioning",
      "Aeration",
      "Lawn Seeding and Sodding",
      "Garden Bed Design and Installation",
      "Seasonal Flower Planting",
      "Leaf Removal and Yard Clean-Up",
      "Garden Maintenance and Care",
      "Tree and Stump Removal",
      "Irrigation System Installation and Repair",
      "Garden Lighting Installation",
      "Landscape Design and Planning",
      "Rock and Stone Work (Paths, Walls, etc.)",
      "Water Feature Installation (Fountains, Ponds)",
      "Garden Structure Installation (Gazebos, Trellises)",
      "Vegetable Garden Setup and Maintenance",
      "Garden Pest Control",
      "Garden Consultation and Advice",
      "Landscape Maintenance",
      "Landscape Renovation and Makeovers",
      "Xeriscaping (Water-Efficient Landscaping)",
      "Mulch and Compost Delivery",
      "Green Waste and Debris Removal",
      "Garden and Planting Supplies",
      "Tree and Plant Health Assessment",
      "Garden Irrigation Auditing",
      "Wildlife Management (Deer Repellent, etc.)",
      "Erosion Control and Land Grading",
      "Terracing and Retaining Wall Installation",
      "Garden Rejuvenation and Restoration",
      "Organic Gardening Services",
      "Community and Commercial Gardening Services",
    ],
    pest_control: [
      "Termite Inspection and Treatment",
      "Ant Control",
      "Roach Control",
      "Spider Control",
      "Rodent Control (Rats, Mice, etc.)",
      "Bed Bug Inspection and Treatment",
      "Flea and Tick Control",
      "Mosquito Control",
      "Bee and Wasp Removal",
      "Cockroach Extermination",
      "Moth Control",
      "Silverfish Control",
      "Centipede and Millipede Control",
      "Pantry Pest Control (Weevils, Beetles, etc.)",
      "Bird Control and Bird-Proofing",
      "Squirrel and Raccoon Removal",
      "Snake Control",
      "Wildlife Trapping and Relocation",
      "Bat Removal and Exclusion",
      "Mole and Vole Control",
      "Preventative Pest Control Treatments",
      "Integrated Pest Management (IPM) Services",
      "Green Pest Control (Environmentally Friendly Solutions)",
      "Pest Inspections and Pest Monitoring",
      "Structural Pest Exclusion",
      "Pest-Proofing (Sealing Entry Points)",
      "Nuisance Animal Removal",
      "Attic and Crawl Space Cleaning and Sanitization",
      "Garden and Plant Pest Control",
      "Exterior Perimeter Treatment",
      "Indoor Pest Control Services",
      "Commercial Pest Control Services",
      "Residential Pest Control Services",
      "Restaurant and Food Service Pest Control",
      "Hospital and Healthcare Facility Pest Control",
      "Hotel and Hospitality Pest Control",
      "School and Educational Facility Pest Control",
      "Warehouse and Industrial Pest Control",
      "Property Management Pest Control",
      "Pest Control Consultation and Advice",
      "Emergency Pest Control Services",
    ],
    carpet_cleaning: [
      "Steam Carpet Cleaning",
      "Dry Carpet Cleaning",
      "Hot Water Extraction",
      "Carpet Shampooing",
      "Carpet Stain Removal",
      "Carpet Odor Removal",
      "Deep Carpet Cleaning",
      "Pet Stain and Odor Treatment",
      "Carpet Sanitization",
      "Carpet Deodorization",
      "Carpet Protection and Scotchgard Application",
      "Area Rug Cleaning",
      "Upholstery Cleaning",
      "Mattress Cleaning",
      "Carpet Inspection and Evaluation",
      "Carpet Pre-Treatment",
      "Carpet Grooming",
      "Carpet Drying",
      "Carpet Repair (Patching, Re-stretching, etc.)",
      "Carpet Maintenance Plans",
      "Carpet Vacuuming",
      "Carpet Spot Cleaning",
      "Carpet Traffic Lane Cleaning",
      "High-Traffic Area Cleaning",
      "Green Carpet Cleaning (Environmentally Friendly Solutions)",
      "Carpet Cleaning for Commercial Spaces",
      "Carpet Cleaning for Residential Spaces",
      "Carpet Cleaning for Offices and Businesses",
      "Carpet Cleaning for Hotels and Hospitality",
      "Carpet Cleaning for Schools and Educational Facilities",
      "Carpet Cleaning for Healthcare Facilities",
      "Carpet Cleaning for Restaurants",
      "Carpet Cleaning for Property Management",
      "Carpet Cleaning for Rental Properties",
      "Emergency Carpet Cleaning Services",
      "Carpet Cleaning Consultation and Estimates",
    ],
    catering_services: [
      "Event Menu Planning",
      "Food Preparation and Cooking",
      "Appetizers and Hors d'oeuvres",
      "Buffet-style Catering",
      "Plated Meal Service",
      "Family-style Meal Service",
      "Food Stations (e.g., Carving Stations, Pasta Stations)",
      "Dessert Buffets",
      "Beverage Service (Alcoholic and Non-Alcoholic)",
      "Cocktail Receptions",
      "Bartending Services",
      "Specialty Drink and Signature Cocktail Creation",
      "Full-Service Catering",
      "Drop-off Catering",
      "Corporate Catering",
      "Wedding Catering",
      "Social Event Catering (Birthdays, Anniversaries, etc.)",
      "Holiday Party Catering",
      "BBQ and Outdoor Catering",
      "Brunch Catering",
      "Breakfast Catering",
      "Lunch Catering",
      "Dinner Catering",
      "Boxed Lunches and Sandwich Platters",
      "Vegetarian and Vegan Catering",
      "Gluten-free and Allergen-friendly Catering",
      "International Cuisine Catering",
      "Catering for Dietary Restrictions",
      "Customized Menus",
      "Food Tasting and Menu Selection",
      "Food Presentation and Styling",
      "Tableware and Linen Rental",
      "Event Staffing (Servers, Bartenders, etc.)",
      "Event Coordination and Planning",
      "Vendor Coordination (e.g., Rentals, Flowers)",
      "Cleanup and Post-event Services",
      "Venue Selection Assistance",
      "Food Truck Catering",
      "Catering for Large Events and Banquets",
      "Catering for Small Intimate Gatherings",
      "Green and Sustainable Catering Practices",
    ],
    fitness_trainer: [
      "Personal Training Sessions",
      "Group Fitness Classes",
      "Individualized Workout Plans",
      "Fitness Assessments and Evaluations",
      "Strength Training",
      "Cardiovascular Conditioning",
      "Flexibility and Mobility Training",
      "Weight Loss Programs",
      "Muscle Building and Bodybuilding",
      "Endurance and Stamina Training",
      "Core Strengthening Exercises",
      "Functional Training",
      "Balance and Coordination Exercises",
      "Sports-specific Training",
      "HIIT (High-Intensity Interval Training)",
      "Plyometric Exercises",
      "Circuit Training",
      "Kettlebell Training",
      "TRX Suspension Training",
      "Boxing and Kickboxing Workouts",
      "Yoga and Pilates Instruction",
      "Stretching and Warm-up Routines",
      "Nutrition Guidance and Meal Planning",
      "Weight Management Coaching",
      "Fitness Goal Setting and Tracking",
      "Body Composition Analysis",
      "Injury Prevention and Rehabilitation",
      "Fitness Coaching for Special Populations (Seniors, Pregnant Women, etc.)",
      "Online or Virtual Personal Training",
      "Home Workout Programs",
      "Gym or Studio-based Training",
      "Outdoor Fitness Sessions",
      "Fitness Boot Camps",
      "Motivational Support and Accountability",
      "Fitness Workshops and Seminars",
      "Wellness and Lifestyle Coaching",
      "Fitness Consultations and Assessments",
      "Posture Correction and Alignment Exercises",
      "Fitness for Postnatal and Postpartum Women",
      "Stress Reduction and Relaxation Techniques",
      "Fitness Education and Instructional Videos",
      "Customized Fitness Plans for Specific Goals",
      "Holistic and Mind-Body Fitness Approaches",
    ],
    event_planning: [
      "Event Conceptualization and Design",
      "Venue Selection and Booking",
      "Budget Planning and Management",
      "Vendor Coordination and Management",
      "Event Logistics and Timeline Planning",
      "Theme and Decor Planning",
      "Invitation Design and Management",
      "Guest List Management and RSVPs",
      "Entertainment Booking (Musicians, DJs, Performers)",
      "Catering Services and Menu Planning",
      "Beverage Services and Bar Management",
      "Audio-Visual and Lighting Setup",
      "Event Rentals (Furniture, Linens, etc.)",
      "Event Staffing (Ushers, Greeters, etc.)",
      "On-site Event Coordination",
      "Event Registration and Ticketing",
      "Transportation and Parking Arrangements",
      "Photography and Videography Services",
      "Event Marketing and Promotion",
      "Social Media Management for Events",
      "Event Security and Crowd Control",
      "Health and Safety Planning (COVID-19 protocols, etc.)",
      "Event Sponsorship and Partnership Coordination",
      "Speaker and Presenter Management",
      "Gifts and Favors Coordination",
      "Signage and Branding",
      "Audio-Visual Equipment Rental and Setup",
      "Event Permitting and Legal Compliance",
      "Post-event Evaluation and Analysis",
      "Virtual and Hybrid Event Planning",
      "Event Consulting and Advisory Services",
      "Corporate Event Planning",
      "Wedding Planning",
      "Social Event Planning (Birthdays, Anniversaries, etc.)",
      "Non-profit and Fundraising Event Planning",
      "Conference and Trade Show Planning",
      "Exhibition and Product Launch Planning",
      "Gala and Awards Ceremony Planning",
      "Team Building Events",
      "Workshop and Seminar Planning",
      "Fashion Show and Runway Event Planning",
      "Charity and Benefit Event Planning",
      "Destination Event Planning",
      "Event Theme and Decor Execution",
      "Green and Sustainable Event Planning",
    ],
    interior_design: [
      "Space Planning and Layout Design",
      "Color Consultation and Selection",
      "Furniture Selection and Arrangement",
      "Custom Furniture Design",
      "Window Treatments and Curtains",
      "Flooring Selection and Design",
      "Wall Coverings and Paint Selection",
      "Lighting Design and Fixtures",
      "Artwork and Accessories Selection",
      "Home Decor and Styling",
      "Kitchen Design and Renovation",
      "Bathroom Design and Remodeling",
      "Bedroom Design and Makeover",
      "Living Room Design",
      "Dining Room Design",
      "Home Office Design",
      "Children's Room Design",
      "Nursery Design",
      "Outdoor and Patio Design",
      "Entryway and Foyer Design",
      "Home Renovation and Remodeling",
      "Interior Architectural Detailing",
      "Custom Cabinetry and Built-ins",
      "Material and Finish Selection",
      "Space Optimization for Storage",
      "Wall and Ceiling Design (including wallpaper and textures)",
      "Fireplace Design and Mantels",
      "Home Theater and Entertainment Room Design",
      "Lighting Fixtures and Controls",
      "Smart Home Integration and Automation",
      "Sustainable and Eco-friendly Design",
      "Universal Design and Accessibility",
      "Interior Design for Commercial Spaces (Offices, Retail, Restaurants, etc.)",
      "Interior Design for Hospitality (Hotels, Resorts, Bars, etc.)",
      "Interior Design for Healthcare Facilities",
      "Interior Design for Educational Facilities",
      "Interior Design for Exhibition and Showroom Spaces",
      "Interior Design for Event and Pop-up Spaces",
      "Interior Design Consultations and Design Planning",
      "Project Management and Coordination",
      "Visualization and 3D Rendering",
      "Budgeting and Cost Estimation for Interior Projects",
      "Interior Styling and Home Staging",
      "Conceptual Mood Boards and Design Proposals",
    ],
  };
  const cities = [
    "Mumbai, Delhi, Bengaluru",
    "Delhi, Bengaluru, Kolkata",
    "Bengaluru, Kolkata, Chennai",
    "Kolkata, Chennai, Hyderabad",
    "Chennai, Hyderabad, Ahmedabad",
    "Hyderabad, Ahmedabad, Pune",
    "Ahmedabad, Pune, Surat",
    "Pune, Surat, Jaipur",
    "Surat, Jaipur, Mumbai",
    "Jaipur, Mumbai, Bengaluru",
  ];

  const getRandomCity = () => {
    return cities[Math.floor(Math.random() * cities.length)];
  };

  const [searchQuery, setSearchQuery] = useState("");
  const [searchCity, setSearchCity] = useState("");
  const servicesList = servicesData[service] || [];

  const filteredServices = servicesList.filter(
    (item) =>
      item.toLowerCase().includes(searchQuery.toLowerCase()) &&
      getRandomCity().toLowerCase().includes(searchCity.toLowerCase())
  );

  const getRandomPrice = () => {
    //return Math.floor(Math.random() * (999 - 99 + 1)) + 99;
    const actualPrice = Math.floor(Math.random() * (999 - 99 + 1)) + 99;
    return actualPrice;
  };

  const getRandomRating = () => {
    return (Math.random() * (5.0 - 3.0) + 3.0).toFixed(1);
  };

  return (
    <div className="services-list-page">
      <h2>Services offered in {service} department:-</h2>
      <div className="search-container">
        <input
          type="text"
          placeholder="Search for a service..."
          value={searchQuery}
          onChange={(e) => setSearchQuery(e.target.value)}
        />
        <input
          type="text"
          placeholder="Search for a city..."
          value={searchCity}
          onChange={(e) => setSearchCity(e.target.value)}
        />
      </div>
      {servicesList.length === 0 ? (
        <p>No services found for {service}.</p>
      ) : (
        <div className="services-container">
          {filteredServices.map((item, index) => (
            <div className="service-card" key={index}>
              <h3>{item}</h3>
              <p>Rating: {getRandomRating()} / 5.0</p>
              <p>Price: ₹{getRandomPrice()}</p>
              <p>City: {getRandomCity()}</p>
              <Link to={`/booking?service=${encodeURIComponent(item)}`}>
                <button className="book-now-button">Book Now</button>
              </Link>
            </div>
          ))}
        </div>
      )}
    </div>
  );
};

export default ServicesListPage;
